language: go
dist: xenial
go:
- go1.13

sudo: required
install: true

env:
- CHANGE_MINIKUBE_NONE_USER=true

before_install:
  - make before_install

before_script:
  - make before_script

script:
  - make script
  
deploy:
  - provider: script
    script: make deploy
    on:
      branch: master
  - provider: pages
    local-dir: build
    skip-cleanup: true
    keep-history: true
    github-token: $GITHUB_TOKEN
    committer-from-gh: true
    on:
      branch: master